haskell-streaming/streaming

src/Streaming/Internal.hs
src/Streaming/Prelude.hs

Original PR text from @treeowl:
> It's simpler, and very often faster, to use `m >>= f` instead of `join (fmap f m)`.

join + fmap = bind

---

src/Streaming.hs
src/Streaming/Internal.hs
src/Streaming/Prelude.hs

`copy` can be generalized considerably.
```haskell
copy :: Monad m => Stream (Of a) m r -> Stream (Of a) (Stream (Of a) m) r
```
would generalize immediately to
```haskell
copy :: (Monad m, Extend f)
=> Stream f m r -> Stream f (Stream f m) r
```
where `Extend` is just `Comonad` without `extract`. We don't currently
depend on `semigroupoids` or `comonad`, however, so that's not a viable
option. Fortunately, we can generalize still further, producing
```haskell
expand :: (Monad m, Functor f)
=> (forall a b. (g a -> b) -> f a -> h b)
-> Stream f m r -> Stream g (Stream h m) r
```
and (with our foot on the other `Functor`)
```haskell
expandPost :: (Monad m, Functor g)
=> (forall a b. (g a -> b) -> f a -> h b)
-> Stream f m r -> Stream g (Stream h m) r

Generalize copy to expand

---

src/Streaming.hs
src/Streaming/Internal.hs
src/Streaming/Prelude.hs

Sometimes, the target functor of `maps` or `mapped` offers
a more efficient `fmap` than the source functor. Add versions
of `maps`, `mapped`, and `mapsM` that use that one instead.
Add explicitly "unsafe" `hoistUnexposed` and `hoistUnexposed2`.
Add "safe" `hoistUnexposed`.

Add differently-constrained maps and mapped

---

src/Streaming/Internal.hs

`destroy` was defined exactly the same as `destroyExposed`,
allowing users to distinguish between streams depending on their
`Effect` layering. Now I *believe* it hides this implementation
detail properly.
Fixes #9.

Make destroy respect the abstraction

---

src/Streaming.hs
src/Streaming/Internal.hs

Explain how `iterT` and `iterTM` can be defined in terms of
each other.

Add more docs for iterT and iterTM

---

changelog.md
src/Streaming/Internal.hs

`mapsExposed` was just a copy of `maps`, and `mapsMExposed` was just
a copy of `mapsM`. As far as I can tell, neither of them does anything
that exposes the abstraction, so there's no point in having these
scarily-named versions.
Fixes #7

Deprecate mapsExposed and mapsMExposed

---

changelog.md
src/Data/Functor/Of.hs
src/Streaming/Internal.hs
streaming.cabal

Made the `Show` and `Eq` instances for `Stream` respect the
abstraction. In effect, the streams are `unexposed` before
being shown or tested for equality.
Added `Eq1`, `Ord`, `Ord1`, and `Show1` instances for `Stream`.
Added `Generic`, `Generic1`, `Eq1`, `Ord1`, `Show1`, `Eq2`, `Ord2`,
and `Show2` instances for `Of`.
Fixes #3

Add and improve instances

---

streaming.cabal

Currently, the changelog isn't bundled with the source distribution, which prevents the changelog from being displayed on Hackage. This adds `changelog.md` to `extra-source-files` to correct this.

Add changelog.md to extra-source-files

---

.gitignore
changelog.md
src/Data/Functor/Of.hs
src/Streaming/Internal.hs
streaming.cabal

Currently, `streaming-0.2.0.0` fails to build on GHC 8.4.1 since `Semigroup` has become a superclass of `Monoid`, and `Of` and `Stream` lack `Semigroup` instances. This fixes the issue.
I opted to avoid some CPP by depending on the `semigroups` package to provide the `Semigroup` class on GHC 7.10 (before `Semigroup` was added to `base`). If you'd prefer to avoid incurring an extra dependency, I could alternatively remove the `semigroups` dependency and only define the `Semigroup` instances on `base-4.9` or later (at the cost of some CPP).

Add Semigroup instances for Of and Stream

---

README.md

Seems like a good idea to have a highly visible link to the Hackage package at the top and we might as well use a "proper" badge with a version number.

Add Hackage badge to README

---

changelog.md
src/Streaming/Prelude.hs
stack.yaml
streaming.cabal

Closes #43.
*  We might also add `nub`, `nubBy`, `nubOn` for types with only `Eq`, but I didn't attempt it.  I suppose they'd be pretty inefficient unless the stream is mostly duplicates (but that is a valid use case).
*  Per discussion, I followed the naming conventions from `containers`, rather than the previous naming.  Although, I noticed [`Control.Foldl`](https://hackage.haskell.org/package/foldl-1.3.7/docs/Control-Foldl.html#v:nub) uses a "reverse" convention (`nub` for the `Ord` instance, `eqNub` for `Eq`-only).
*  The code and documentation are largely based on (or outright copied from) `nub` from the past version of `streaming`.
*  Unrelated docs fix (traversable -> foldable).
*  There is some code repetition between the `Ord` and `Int` versions.  Possibly these could be factored …

Add nubOrd, nubInt, nubOrdOn, nubIntOn.

---

src/Streaming/Internal.hs
src/Streaming/Prelude.hs

Fixes #47.
The default `*>` implementation causes the `S.for` not to be tail recursive. This should be tested against base == 4.8, I'm not 100% sure this is backwards compatibile.

Fixes performance problem with S.concat

---

src/Streaming/Prelude.hs

These functions provide an efficient way to merged ordered streams of elements while preserving their order. The `merge`/`mergeOn`/`mergeBy` pattern is inspired by `sort`/`sortOn`/`sortBy` from `Data.List`.
The actual implementation of `mergeBy` is closely based on `zipWith` and should have roughly the same performance characteristics.

Implemented merge, mergeOn and mergeBy in Streaming.Prelude.

---

changelog.md

adds everything not added to the changelog since march of 2018

add missing stuff to changelog

---

src/Data/Functor/Of.hs
src/Streaming.hs
src/Streaming/Internal.hs
src/Streaming/Prelude.hs
streaming.cabal

I noticed a couple of things that can stand some improvements, so I applied a few (hopefully uncontroversial) improvements. I also noticed that there's no test suite except doctests, so I tried to run doctest on the package but that basically failed. I tried to fix doctests but the package is still left in a condition where it's not possible to just run doctests on it and expects the process to complete.
The problem with doctests is that many doctests read from `stdin` and there's no way to specify custom stdin for doctests yet (some tests specify stdin contents interleaved with stdout contents, which will be even harder to specify for the tool). I tried disabling those and fix the rest but the disabling changed how haddock documentation looks. So I fixed all doctest issues I encountered …

Fix build with 7.10.3 and fix doctests

---

src/Streaming/Prelude.hs

The existing untilRight function feels opposite of the usual interpretation of Either, where Left contains the error and Right contains the interesting data.

Add untilLeft function that mirrors untilRight

---

changelog.md
streaming.cabal

The conditional was already there for `fail`. It makes sense to only
incur the dependency on compatibility packages when needed, so let's
add `semigroups` to the conditional set, instead of depending on it unconditionally.

Only depend on semigroups on old GHCs.

---

src/Streaming.hs
src/Streaming/Internal.hs
src/Streaming/Prelude.hs

Kudos! The haddocks for this library are superior to what's commonly available on hackage.
While reading the docs and playing with the examples I found various minor mistakes that I'm fixing in this PR. I'll probably submit more fixes in the future if you like it.

Various documentation improvements

---

src/Streaming/Prelude.hs

Fix small typo in documentation of splitAt

---

src/Streaming/Prelude.hs

Two changes to the documentation of [`Streaming.Prelude.mapped`](http://hackage.haskell.org/package/streaming-0.2.3.0/docs/Streaming-Prelude.html#v:mapped):
One, remove the example transformation:
> let noteBeginning text x = putStrLn text >> return text
Because it doesn't seem to correspond to any transformation actually accepted by `mapped`.
Two, add documentation for a frequent use case: handling groups defined in effectful `IO`-based streams. `mapped` is the function to use in such cases, but it isn't obvious at all because it is functor-general.

Changes to the documentation of `Streaming.Prelude.mapped`

---

src/Streaming/Prelude.hs
streaming.cabal
test/test.hs

These functions are like (S.map Foldable.minimum (S.slidingWindow n s)) but
far more efficient.

Add slidingWindow{Min,Max}{By,} functions

---

src/Streaming/Prelude.hs

This corrects issue #91 about inaccurate enumFrom documentation by changing the example. I've also slightly reworded the text.

corrected documentation for enumFrom

---

src/Streaming/Prelude.hs

This solves a problem in the haddocks noticed by @chowells79 in issue #97. Some lambda slashes were not being rendered in code samples.
The reason—[according to the docs](https://haskell-haddock.readthedocs.io/en/latest/markup.html#code-blocks)—is that lambda slashes in code blocks delimited with `@` must be escaped.

Escaped lambda slashes inside code blocks.

---

src/Streaming/Internal.hs

The change is motivated by https://github.com/haskell/core-libraries-committee/issues/10, but I think it's good on its own, because implementation gets deduplicated.

Share code between Show (Stream f m r) and Show1 (Stream f m)

---

streaming.cabal

Everything works as expected locally when running `cabal test all --enable-tests --constraint="mtl==2.3.*" --constraint="transformers==0.6.*"`.

Allow building with `mtl-2.3.*` and `transformers-0.6.*`

---

src/Data/Functor/Of.hs

This fixes a warnings when building with `base >=4.18.0.0`.

Define >> for Of in terms of *>
